# Generated by Django 4.2.1 on 2023-05-28 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='title_left',
            new_name='left_title',
        ),
        migrations.RenameField(
            model_name='header',
            old_name='title_right',
            new_name='right_title',
        ),
    ]
