# Generated by Django 4.2.1 on 2023-05-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_title_left_header_left_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFirstPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos', verbose_name='Background Video')),
                ('left_title', models.CharField(max_length=40, verbose_name='Left Title')),
                ('right_title', models.CharField(max_length=40, verbose_name='Right Title')),
                ('subtitle1', models.CharField(max_length=50, verbose_name='Subtitle 1')),
                ('subtitle2', models.CharField(max_length=50, verbose_name='Subtitle 2')),
            ],
            options={
                'verbose_name': 'Home First Page',
                'verbose_name_plural': 'Home First Page',
            },
        ),
    ]
