# Generated by Django 4.2.1 on 2023-05-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_homefirstpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighLights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('video_link', models.URLField(verbose_name='Video Link')),
            ],
        ),
    ]
