# Generated by Django 4.2.1 on 2023-05-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_highlights'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_title', models.CharField(max_length=40, verbose_name='Left Title')),
                ('right_title', models.CharField(max_length=40, verbose_name='Right Title')),
                ('subtitle', models.CharField(max_length=80, verbose_name='Subtitle')),
                ('text1', models.TextField(verbose_name='Text 1')),
                ('text2', models.TextField(verbose_name='Text 2')),
                ('left_btn', models.CharField(max_length=40, verbose_name='Left Button')),
                ('right_btn', models.CharField(max_length=40, verbose_name='Right Button')),
                ('img1', models.ImageField(upload_to='images', verbose_name='Image 1')),
                ('img2', models.ImageField(upload_to='images', verbose_name='Image 2')),
                ('img3', models.ImageField(upload_to='images', verbose_name='Image 3')),
                ('img4', models.ImageField(upload_to='images', verbose_name='Image 4')),
                ('info', models.CharField(max_length=80, verbose_name='Info 1')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.AlterModelOptions(
            name='highlights',
            options={'verbose_name': 'HighLights', 'verbose_name_plural': 'HighLights'},
        ),
    ]
