# Generated by Django 4.2.1 on 2023-05-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_about_alter_highlights_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_title', models.CharField(max_length=40, verbose_name='Left Title')),
                ('right_title', models.CharField(max_length=40, verbose_name='Right Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('profession', models.CharField(max_length=60, verbose_name='Profession')),
                ('social1', models.CharField(blank=True, max_length=50, verbose_name='Social 1')),
                ('social_url1', models.URLField(blank=True, verbose_name='Social Url 1')),
                ('social2', models.CharField(blank=True, max_length=50, verbose_name='Social 2')),
                ('social_url2', models.URLField(blank=True, verbose_name='Social Url 2')),
                ('social3', models.CharField(blank=True, max_length=50, verbose_name='Social 3')),
                ('social_url3', models.URLField(blank=True, verbose_name='Social Url 3')),
            ],
            options={
                'verbose_name': 'Speakers',
                'verbose_name_plural': 'Speakers',
            },
        ),
        migrations.CreateModel(
            name='SpeakersContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('profession', models.CharField(max_length=60, verbose_name='Profession')),
                ('social1', models.CharField(blank=True, max_length=50, verbose_name='Social 1')),
                ('social_url1', models.URLField(blank=True, verbose_name='Social Url 1')),
                ('social2', models.CharField(blank=True, max_length=50, verbose_name='Social 2')),
                ('social_url2', models.URLField(blank=True, verbose_name='Social Url 2')),
                ('social3', models.CharField(blank=True, max_length=50, verbose_name='Social 3')),
                ('social_url3', models.URLField(blank=True, verbose_name='Social Url 3')),
            ],
            options={
                'verbose_name': 'Speakers Content',
                'verbose_name_plural': 'Speakers Content',
            },
        ),
    ]
