# Generated by Django 4.2.1 on 2023-05-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_speakers_speakerscontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_title1', models.CharField(max_length=40, verbose_name='Left Title 1')),
                ('right_title1', models.CharField(max_length=40, verbose_name='Right Title 1')),
                ('img', models.ImageField(upload_to='images', verbose_name='Background Image')),
                ('left_title2', models.CharField(max_length=40, verbose_name='Left Title 2')),
                ('right_title2', models.CharField(max_length=40, verbose_name='Right Title 2')),
                ('text', models.TextField(verbose_name='Text')),
                ('btn_name', models.CharField(max_length=40, verbose_name='Button Name')),
            ],
            options={
                'verbose_name': 'Schedules',
                'verbose_name_plural': 'Schedules',
            },
        ),
    ]
