# Generated by Django 4.2.1 on 2023-05-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_scheldulescontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheldulesContent',
        ),
    ]
