# Generated by Django 4.2.1 on 2023-05-29 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_scheldulescontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheldulesContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('profile_img', models.ImageField(upload_to='images', verbose_name='Profile Image')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('profession', models.CharField(max_length=50, verbose_name='Profession')),
                ('time', models.CharField(max_length=50, verbose_name='Time')),
                ('place', models.CharField(max_length=50, verbose_name='Place')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schedulescategories')),
            ],
        ),
    ]
