# Generated by Django 4.2.1 on 2023-05-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_scheldulescontent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheldulescontent',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='scheldulescontent',
            name='profession',
            field=models.CharField(blank=True, max_length=50, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='scheldulescontent',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Profile Image'),
        ),
    ]
