# Generated by Django 4.2.1 on 2023-05-29 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_scheldulescontent_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='path8',
        ),
    ]
