# Generated by Django 4.2.1 on 2023-05-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_header_path8'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_title', models.CharField(max_length=40, verbose_name='Left Title')),
                ('right_title', models.CharField(max_length=40, verbose_name='Right Title')),
                ('google_map', models.URLField(verbose_name='Google Map')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('info1', models.CharField(max_length=80, verbose_name='Info 1')),
                ('info2', models.CharField(max_length=80, verbose_name='Info 2')),
                ('info3', models.CharField(max_length=80, verbose_name='Info 3')),
            ],
            options={
                'verbose_name': 'Venue',
                'verbose_name_plural': 'Venue',
            },
        ),
    ]
