# Generated by Django 4.2.1 on 2023-05-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_venue_google_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_title', models.CharField(max_length=40, verbose_name='Left Title')),
                ('right_title', models.CharField(max_length=40, verbose_name='Right Title')),
                ('btn_name', models.CharField(max_length=40, verbose_name='Button Name')),
            ],
        ),
        migrations.CreateModel(
            name='PricingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('offer1', models.CharField(max_length=80, verbose_name='Offer 1')),
                ('offer2', models.CharField(max_length=80, verbose_name='Offer 2')),
                ('offer3', models.CharField(max_length=80, verbose_name='Offer 3')),
                ('text', models.TextField(verbose_name='Text')),
            ],
        ),
    ]
