# Generated by Django 4.2.1 on 2023-05-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_pricing_pricingcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricing',
            options={'verbose_name': 'Pricing', 'verbose_name_plural': 'Pricing'},
        ),
        migrations.AlterField(
            model_name='pricingcontent',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
    ]
