# Generated by Django 4.2.1 on 2023-05-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_contactget_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle1', models.CharField(max_length=50, verbose_name='Subtitle 1')),
                ('subtitle2', models.CharField(max_length=50, verbose_name='Subtitle 2')),
                ('subtitle3', models.CharField(max_length=50, verbose_name='Subtitle 3')),
                ('subtitle4', models.CharField(max_length=50, verbose_name='Subtitle 4')),
                ('social1', models.CharField(max_length=40, verbose_name='Social 1')),
                ('social_url1', models.URLField(verbose_name='Social Url 1')),
                ('social2', models.CharField(max_length=40, verbose_name='Social 2')),
                ('social_url2', models.URLField(verbose_name='Social Url 2')),
                ('social3', models.CharField(max_length=40, verbose_name='Social 3')),
                ('social_url3', models.URLField(verbose_name='Social Url 3')),
                ('social4', models.CharField(max_length=40, verbose_name='Social 4')),
                ('social_url4', models.URLField(verbose_name='Social Url 4')),
                ('copyright1', models.TextField(verbose_name='Copyright 1')),
                ('copyright2', models.TextField(verbose_name='Copyright 2')),
                ('design', models.CharField(max_length=50, verbose_name='Design')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('name_link', models.URLField(verbose_name='Name Link')),
            ],
        ),
    ]
